### ISSUE TITLE
Anchors Don't Work on Slice1-only Pages

### ISSUE THREAD

**Issue by InsertCreativityHere** [icerpc/icerpc-docs#374]
https://docs.icerpc.dev/slice1/language-guide/class-types#slicing
Should automatically jump down to the 'slicing' section of the class page, but instead it stays at the top of the page.
This happens for any anchor on the classes and exception pages.

But it doesn't seem to happen on other page except these 2.
I suspect it's because they're Slice1 only.

**Comment by ReeceHumphreys** [comment]
Given that the anchors do work when clicking the links in the right side table of contents I think this is actually a client side rendering issue. It seems that both of those pages only load the main contents of the docs on the client. So when you first go to the url of the page, there is no content for a brief second - thus it does not know where to jump to when you first load the page.

**Comment by ReeceHumphreys** [comment]
Yes, `ModeSection` is a client only component and since these entire pages are just one big `ModeSection` everything is client rendered. This will require some under the hood reworking to see if we can avoid client rendering these sections.

https://github.com/icerpc/icerpc-docs/blob/58115f7bff9139a179dcf81b76a2614bb01780de/components/tags/mode-section.tsx#L2-L4

**Comment by ReeceHumphreys** [comment]
Fixed by https://github.com/icerpc/icerpc-docs/commit/04cea5131d8229aa1c540e0121ac719320e8d6e9
